[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "1.10.31"
solana-client = "1.10.31"
solana-transaction-status = "1.10.31"
spl-token = "3.*.*"
spl-associated-token-account = "1.0.*"
axum = "0.5.*"
tokio = { version = "1.14.*", features = ["full"] }
hyper = { version = "0.14.*", features = ["full"] }
serde = "1.0.*"
serde_json = "1.0.*"
serde_with = "1.12.*"
bincode = "1.3.*"
sqlite = "0.26.*"
anyhow = "1.0.*"
hex-literal = "0.3.*"

[workspace]
